apiVersion: configplane.juniper.net/v1
kind: Configlet
metadata:
  name: configlet-jcnr2
  namespace: jcnr
spec:
  config: |-
    set interfaces lo0 unit 0 family iso address 49.0001.0000.0000.0002.00
    set interfaces lo0 unit 0 family inet address 1.1.1.2/32
    set interfaces ens4 unit 0 family inet address 192.168.1.2/24
    set interfaces ens4 unit 0 family iso
    set routing-options router-id 1.1.1.2
    set routing-options route-distinguisher-id 1.1.1.2
    set protocols isis interface ens4
    set protocols isis interface lo0.0
    set protocols bgp group jcnrbgp1 type internal
    set protocols bgp group jcnrbgp1 local-address 1.1.1.2
    set protocols bgp group jcnrbgp1 local-as 65000
    set protocols bgp group jcnrbgp1 neighbor 1.1.1.1
    set protocols bgp group jcnrbgp1 family evpn signaling
    set protocols bgp group jcnrbgp1 vpn-apply-export
    set routing-instances vrf1 protocols evpn ip-prefix-routes advertise direct-nexthop
    set routing-instances vrf1 protocols evpn ip-prefix-routes encapsulation vxlan
    set routing-instances vrf1 protocols evpn ip-prefix-routes vni 2000
    set routing-instances vrf1 vrf-table-label
    set routing-instances vrf1 protocols evpn ip-prefix-routes export export-static
    set policy-options policy-statement export-static term 1 from protocol static
    set policy-options policy-statement export-static term 1 then accept
