apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vrouter2-2
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "vrouter2-2",
    "plugins": [
      {
        "type": "jcnr",
        "args": {
          "instanceName": "vrouter2-2",
          "instanceType": "virtual-router",
          "interfaceType": "veth"
        },
        "ipam": {
          "type": "host-local",
          "ranges": [
            [
              {
                "subnet": "20.0.0.0/24",
                "gateway": "20.0.0.1"
              }
            ],
            [
              {
                "subnet": "abcd::20.0.0.0/120",
                "gateway": "abcd::20.0.0.1"
              }
            ]
          ],
          "routes": [
            {"dst": "10.0.0.0/24", "gw": "20.0.0.1"},
            {"dst": "abcd::10.0.0.0/120", "gw": "abcd::20.0.0.1"}
          ]
        },
        "kubeConfig":"/etc/kubernetes/kubelet.conf"
      }
    ]
  }'
