apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vswitch3-bd200
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "vswitch3-bd200",
    "plugins": [
      {
        "type": "jcnr",
        "args": {
          "instanceName": "vswitch",
          "instanceType": "virtual-switch",
          "bridgeDomain": "bd200",
          "bridgeVlanId": "200",
          "parentInterface": "net1",
          "interface": "net1.200"
        },
        "ipam": {
          "type": "static",
          "addresses":[
            {
              "address":"20.0.0.2/24",
              "gateway":"20.0.0.1"
            },
            {
              "address":"abcd::20.0.0.2/120",
              "gateway":"abcd::20.0.0.1"
            }
          ]
        },
        "kubeConfig":"/etc/kubernetes/kubelet.conf"
      }
    ]
  }'
