apiVersion: v1
kind: Pod
metadata:
  name: vswitch3-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "vswitch3-bd100",
          "interface": "net1.100",
          "cni-args": {
            "interfaceType":"veth"
          }
        },
        {
          "name": "vswitch3-bd200",
          "interface": "net1.200",
          "cni-args": {
            "interfaceType":"veth"
          }
        }
      ]
spec:
  containers:
  - name: vswitch3-pod1
    image: docker.io/centos
    command: [ "/bin/bash", "-c" ]
    args:
      - sleep infinity;
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
